# theme: jekyll-theme-cayman
title: Hendrik Dreyer
description: Data Scientist

highlighter: rouge

##### BUILD SETTINGS #####
# incremental: true

# strip all unncessary whitespace and comments
compress_html:
  blanklines: true